import Head from 'next/head';
import axios from 'axios';
import { useEffect, useState } from 'react';
import Link from 'next/link';

export default function Home() {
  const [posts, setPosts] = useState([]);
  const [currentPage, setCurrentPage] = useState(1);
  const totalPage = 10;
  const pages = Array.from(Array(totalPage), (_, i) => i + 1);

  // https://gorest.co.in/public/v2/posts?page=1&per_page=10
  async function getData(value) {
    const response = await axios.get(`https://gorest.co.in/public/v2/posts`, {
      params: {
        page: value ? value : currentPage,
        per_page: 10,
      },
    });
    const result = response.data;
    setPosts(result);
  }

  useEffect(() => {
    getData();
  }, [currentPage]);

  function nextPage() {
    setCurrentPage(currentPage + 1);
  }

  function previousPage() {
    setCurrentPage(currentPage - 1);
  }

  function goToPage(p) {
    setCurrentPage(p);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container mx-auto mt-4">
          <ul className="space-y-3">
            {posts.map((post, index) => (
              <Link href={`/blog/${post.id}`} key={post.id}>
                <div className="p-4 border rounded-xl">
                  <li>
                    {index + 1}. {post.title}
                  </li>
                </div>
              </Link>
            ))}
          </ul>
        </div>
        <button
          className="px-4 py-2 border rounded-md"
          onClick={previousPage}
          disabled={currentPage === 1}
        >
          prev
        </button>
        {pages.map((page) => (
          <button
            key={page}
            className="px-4 py-2 border rounded-md"
            onClick={() => goToPage(page)}
            disabled={currentPage === page}
          >
            {page}
          </button>
        ))}
        <button
          className="px-4 py-2 border rounded-md"
          onClick={nextPage}
          disabled={currentPage === totalPage}
        >
          next
        </button>
      </main>
    </>
  );
}
